### PR TITLE
update tExpire upon value request (getItem)

### PR DESCRIPTION
**Pull request by Hjortsberg**

### CODE REVIEW

**Comment by Hjortsberg** [comment]
Ah, nice. Updating the expiration time creates a datarace. need to debug

**Comment by optmzr** [comment]
That's because you're holding a read lock and changing. Change to a regular lock.

**Comment by Hjortsberg** [comment]
> That's because you're holding a read lock and changing. Change to a regular lock.

Just noticed the same :D fix is already pushed :D

**Comment by optmzr** [comment]
Already approved 💪

**Comment by Hjortsberg** [comment]
fixes: #78

**Pull request merged**
